version: '3.10'

services:
  backend:
    restart: always
    container_name: backend
    build: 
      context: ./backend
    command: python backendFastApi
    volumes:
      -.:/backend/data/
    ports:
      - 8079:8079
    expose:
      - 8079

  frontend:
    restart: always
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 8080:8080
    expose:
      - 8080

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=test